name: Linter

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  golangci-lint:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Must be specified without patch version: we always use the latest patch version.
          version: v2.4

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
