name: Release with goreleaser
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unshallow Fetch
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: release-drafter/release-drafter@v5
        id: rd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare changlog
        run: |
          echo "${{ steps.rd.outputs.body }}" > /tmp/CHANGELOG.md

      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --release-notes=/tmp/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Note: The standard setting for the repository doesn't allow the default GITHUB_TOKEN to be used here
        # Either define a separate Personal Access Token or permit the default GITHUB_TOKEN read/write access
        # see section "Workflow permissions" on https://github.com/mpapenbr/go-racelogger/settings/actions
