name: Release with goreleaser
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
jobs:
  goreleaser:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Unshallow Fetch
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: release-drafter/release-drafter@v6
        id: rd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare changlog
        shell: bash
        run: |
          echo "${{ steps.rd.outputs.body }}" > "${{ runner.temp }}/CHANGELOG.md"

      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --release-notes="${{ runner.temp }}/CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Note: The standard setting for the repository doesn't allow the default GITHUB_TOKEN to be used here
        # Either define a separate Personal Access Token or permit the default GITHUB_TOKEN read/write access
        # see section "Workflow permissions" on https://github.com/mpapenbr/go-racelogger/settings/actions
