name: Release with goreleaser
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
jobs:
  goreleaser:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7
        id: rd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare cosign installer
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        
      - name: prepare changlog
        shell: bash
        run: |
          echo "${{ steps.rd.outputs.body }}" > "${{ runner.temp }}/CHANGELOG.md"

      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          args: release --release-notes="${{ runner.temp }}/CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Note: The standard setting for the repository doesn't allow the default GITHUB_TOKEN to be used here
        # Either define a separate Personal Access Token or permit the default GITHUB_TOKEN read/write access
        # see section "Workflow permissions" on https://github.com/mpapenbr/go-racelogger/settings/actions
      - name: Attest checksums
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4
        with:
          subject-checksums: dist/checksums.txt
